### ISSUE TITLE
Bug Report: Job using cimg/aws:2023.07.1 for ARM64 cannot run steps

### ISSUE THREAD

**Issue by kelvintaywl** [CircleCI-Public/cimg-aws#19]
---

**Describe the bug**

When using the `cimg/aws:2023.07.1` image for a Docker executor job (& specifying for ARM), the job failed with no steps run.
See failed job here:
https://app.circleci.com/pipelines/github/kelvintaywl-cci/open-arms/18/workflows/5afa415c-929f-4612-acd3-2c57c9c8296d/jobs/45

**To Reproduce**

Here is the minimal config to reproduce:

```yaml
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/aws:2023.07.1
    resource_class: arm.large
    steps:
      - run: |
          uname -m
```

**Expected behavior**

It should run as with other supported ARM-available images like `cimg/base:current` :
https://app.circleci.com/pipelines/github/kelvintaywl-cci/open-arms/18/workflows/5afa415c-929f-4612-acd3-2c57c9c8296d/jobs/47

**Workarounds**

> Are there any current workarounds for this bug that can be used currently?

Not that I am aware of yet!

**Screenshots and Build Links**
If possible, add screenshots and links to jobs to help explain your problem.

**Additional context**

I observed that the [other "main" images listed on our Discuss](https://discuss.circleci.com/t/product-launch-arm-docker-preview/48601) ran fine.
(related workflow [here](https://app.circleci.com/pipelines/github/kelvintaywl-cci/open-arms/18/workflows/5afa415c-929f-4612-acd3-2c57c9c8296d))
